version: 2
jobs:
  build:
    docker:
    - image: cimg/go:1.18
    - image: cimg/postgres:15.1.0
      environment: # environment variables for primary container
        POSTGRES_USER: postgres
        DOCKERHUB_USERNAME: animizia
        DOCKERHUB_PASSWORD: asilaydying99@
    steps:
    - checkout
    - run:
        name: Get all dependencies
        command: |
          go get -v ./...
          go get -u github.com/onsi/ginkgo/ginkgo
          go get -u github.com/onsi/gomega/...
    - run:
        name: Test everything
        command: ginkgo -r -race -failFast -progress
    - setup_remote_docker:
        docker_layer_caching: true
    - run:
        name: build and push Docker images
        shell: /bin/bash
        command: |
          chmod +x ./build.sh
          ./build.sh





