// Code generated by protoc-gen-go. DO NOT EDIT.
// source: feed.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventType int32

const (
	EventType_POST_ADDED   EventType = 0
	EventType_POST_UPDATED EventType = 1
	EventType_POST_DELETED EventType = 2
)

var EventType_name = map[int32]string{
	0: "POST_ADDED",
	1: "POST_UPDATED",
	2: "POST_DELETED",
}

var EventType_value = map[string]int32{
	"POST_ADDED":   0,
	"POST_UPDATED": 1,
	"POST_DELETED": 2,
}

func (x EventType) String() string {
	return proto.EnumName(EventType_name, int32(x))
}

func (EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{0}
}

type GetFeedRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	StartToken           string   `protobuf:"bytes,2,opt,name=startToken,proto3" json:"startToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFeedRequest) Reset()         { *m = GetFeedRequest{} }
func (m *GetFeedRequest) String() string { return proto.CompactTextString(m) }
func (*GetFeedRequest) ProtoMessage()    {}
func (*GetFeedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{0}
}

func (m *GetFeedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFeedRequest.Unmarshal(m, b)
}
func (m *GetFeedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFeedRequest.Marshal(b, m, deterministic)
}
func (m *GetFeedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFeedRequest.Merge(m, src)
}
func (m *GetFeedRequest) XXX_Size() int {
	return xxx_messageInfo_GetFeedRequest.Size(m)
}
func (m *GetFeedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFeedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFeedRequest proto.InternalMessageInfo

func (m *GetFeedRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetFeedRequest) GetStartToken() string {
	if m != nil {
		return m.StartToken
	}
	return ""
}

type Event struct {
	EventType            EventType            `protobuf:"varint,1,opt,name=eventType,proto3,enum=pb.EventType" json:"eventType,omitempty"`
	Username             string               `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Url                  string               `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{1}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetEventType() EventType {
	if m != nil {
		return m.EventType
	}
	return EventType_POST_ADDED
}

func (m *Event) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Event) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Event) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type GetFeedResponse struct {
	Events               []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	NextToken            string   `protobuf:"bytes,2,opt,name=nextToken,proto3" json:"nextToken,omitempty"`
	Err                  string   `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFeedResponse) Reset()         { *m = GetFeedResponse{} }
func (m *GetFeedResponse) String() string { return proto.CompactTextString(m) }
func (*GetFeedResponse) ProtoMessage()    {}
func (*GetFeedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7a672c1337cb5ac, []int{2}
}

func (m *GetFeedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFeedResponse.Unmarshal(m, b)
}
func (m *GetFeedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFeedResponse.Marshal(b, m, deterministic)
}
func (m *GetFeedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFeedResponse.Merge(m, src)
}
func (m *GetFeedResponse) XXX_Size() int {
	return xxx_messageInfo_GetFeedResponse.Size(m)
}
func (m *GetFeedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFeedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFeedResponse proto.InternalMessageInfo

func (m *GetFeedResponse) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *GetFeedResponse) GetNextToken() string {
	if m != nil {
		return m.NextToken
	}
	return ""
}

func (m *GetFeedResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterEnum("pb.EventType", EventType_name, EventType_value)
	proto.RegisterType((*GetFeedRequest)(nil), "pb.GetFeedRequest")
	proto.RegisterType((*Event)(nil), "pb.Event")
	proto.RegisterType((*GetFeedResponse)(nil), "pb.GetFeedResponse")
}

func init() { proto.RegisterFile("feed.proto", fileDescriptor_d7a672c1337cb5ac) }

var fileDescriptor_d7a672c1337cb5ac = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xc1, 0x4e, 0x83, 0x40,
	0x10, 0x86, 0x0b, 0xad, 0x55, 0xa6, 0x5a, 0xc9, 0x78, 0x21, 0xc4, 0x68, 0xe5, 0xd4, 0x68, 0x42,
	0x13, 0xf4, 0xe0, 0xc1, 0xc4, 0x34, 0x01, 0xbd, 0x34, 0xb1, 0x41, 0x3c, 0x9b, 0x92, 0x4e, 0x1b,
	0x63, 0x0b, 0xb8, 0xbb, 0x18, 0x7d, 0x17, 0x1f, 0xd6, 0xec, 0x52, 0x16, 0xf1, 0x36, 0xf3, 0xcd,
	0x84, 0xf9, 0x3f, 0x16, 0x60, 0x45, 0xb4, 0xf4, 0x0b, 0x96, 0x8b, 0x1c, 0xcd, 0x22, 0x75, 0xcf,
	0xd7, 0x79, 0xbe, 0xde, 0xd0, 0x44, 0x91, 0xb4, 0x5c, 0x4d, 0xc4, 0xdb, 0x96, 0xb8, 0x58, 0x6c,
	0x8b, 0x6a, 0xc9, 0x9b, 0xc1, 0xf0, 0x91, 0xc4, 0x03, 0xd1, 0x32, 0xa6, 0x8f, 0x92, 0xb8, 0x40,
	0x17, 0x0e, 0x4a, 0x4e, 0x2c, 0x5b, 0x6c, 0xc9, 0x31, 0x46, 0xc6, 0xd8, 0x8a, 0x75, 0x8f, 0x67,
	0x00, 0x5c, 0x2c, 0x98, 0x48, 0xf2, 0x77, 0xca, 0x1c, 0x53, 0x4d, 0xff, 0x10, 0xef, 0xc7, 0x80,
	0xbd, 0xe8, 0x93, 0x32, 0x81, 0x57, 0x60, 0x91, 0x2c, 0x92, 0xef, 0xa2, 0xfa, 0xcc, 0x30, 0x38,
	0xf2, 0x8b, 0xd4, 0x8f, 0x6a, 0x18, 0x37, 0xf3, 0xd6, 0x49, 0xf3, 0xdf, 0x49, 0x1b, 0xba, 0x25,
	0xdb, 0x38, 0x5d, 0x85, 0x65, 0x89, 0xb7, 0x60, 0x69, 0x0b, 0xa7, 0x37, 0x32, 0xc6, 0x83, 0xc0,
	0xf5, 0x2b, 0x4f, 0xbf, 0xf6, 0xf4, 0x93, 0x7a, 0x23, 0x6e, 0x96, 0xbd, 0x25, 0x1c, 0x6b, 0x59,
	0x5e, 0xe4, 0x19, 0x27, 0xbc, 0x80, 0xbe, 0xca, 0xc1, 0x1d, 0x63, 0xd4, 0x1d, 0x0f, 0x02, 0x4b,
	0x87, 0x8c, 0x77, 0x03, 0x3c, 0x05, 0x2b, 0xa3, 0xaf, 0x96, 0x73, 0x03, 0x64, 0x3e, 0x62, 0xac,
	0xce, 0x47, 0x8c, 0x5d, 0xde, 0x83, 0xa5, 0x2d, 0x71, 0x08, 0x30, 0x7f, 0x7a, 0x4e, 0x5e, 0xa7,
	0x61, 0x18, 0x85, 0x76, 0x07, 0x6d, 0x38, 0x54, 0xfd, 0xcb, 0x3c, 0x9c, 0x26, 0x51, 0x68, 0x1b,
	0x9a, 0x84, 0xd1, 0x2c, 0x92, 0xc4, 0x0c, 0xee, 0xa0, 0x27, 0x33, 0xe2, 0x0d, 0xec, 0xef, 0xe2,
	0x22, 0xca, 0x58, 0xed, 0x87, 0x72, 0x4f, 0x5a, 0xac, 0xf2, 0xf1, 0x3a, 0x69, 0x5f, 0xfd, 0x83,
	0xeb, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x10, 0x39, 0xed, 0xf9, 0x0b, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FeedClient is the client API for Feed service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FeedClient interface {
	GetFeed(ctx context.Context, in *GetFeedRequest, opts ...grpc.CallOption) (*GetFeedResponse, error)
}

type feedClient struct {
	cc *grpc.ClientConn
}

func NewFeedClient(cc *grpc.ClientConn) FeedClient {
	return &feedClient{cc}
}

func (c *feedClient) GetFeed(ctx context.Context, in *GetFeedRequest, opts ...grpc.CallOption) (*GetFeedResponse, error) {
	out := new(GetFeedResponse)
	err := c.cc.Invoke(ctx, "/pb.Feed/GetFeed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FeedServer is the server API for Feed service.
type FeedServer interface {
	GetFeed(context.Context, *GetFeedRequest) (*GetFeedResponse, error)
}

// UnimplementedFeedServer can be embedded to have forward compatible implementations.
type UnimplementedFeedServer struct {
}

func (*UnimplementedFeedServer) GetFeed(ctx context.Context, req *GetFeedRequest) (*GetFeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFeed not implemented")
}

func RegisterFeedServer(s *grpc.Server, srv FeedServer) {
	s.RegisterService(&_Feed_serviceDesc, srv)
}

func _Feed_GetFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedServer).GetFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Feed/GetFeed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedServer).GetFeed(ctx, req.(*GetFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Feed_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Feed",
	HandlerType: (*FeedServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFeed",
			Handler:    _Feed_GetFeed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "feed.proto",
}
