# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: feed.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nfeed.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"6\n\x0eGetFeedRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x12\n\nstartToken\x18\x02 \x01(\t\"w\n\x05\x45vent\x12 \n\teventType\x18\x01 \x01(\x0e\x32\r.pb.EventType\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\x12-\n\ttimestamp\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"L\n\x0fGetFeedResponse\x12\x19\n\x06\x65vents\x18\x01 \x03(\x0b\x32\t.pb.Event\x12\x11\n\tnextToken\x18\x02 \x01(\t\x12\x0b\n\x03\x65rr\x18\x03 \x01(\t*?\n\tEventType\x12\x0e\n\nPOST_ADDED\x10\x00\x12\x10\n\x0cPOST_UPDATED\x10\x01\x12\x10\n\x0cPOST_DELETED\x10\x02\x32<\n\x04\x46\x65\x65\x64\x12\x34\n\x07GetFeed\x12\x12.pb.GetFeedRequest\x1a\x13.pb.GetFeedResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'feed_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EVENTTYPE._serialized_start=306
  _EVENTTYPE._serialized_end=369
  _GETFEEDREQUEST._serialized_start=51
  _GETFEEDREQUEST._serialized_end=105
  _EVENT._serialized_start=107
  _EVENT._serialized_end=226
  _GETFEEDRESPONSE._serialized_start=228
  _GETFEEDRESPONSE._serialized_end=304
  _FEED._serialized_start=371
  _FEED._serialized_end=431
# @@protoc_insertion_point(module_scope)
