apiVersion: "nuclio.io/v1beta1"
kind: "NuclioFunction"
spec:
  description: >
    A function that connects to NATS, checks incoming links and publiches PostValid or PostInvalid events.
  runtime: "golang"
  handler: main:Handler
  minReplicas: 1
  maxReplicas: 1
  build:
    commands:
    - apk --update --no-cache add ca-certificates